T_max: 1.0
T_min: 0.0001
total_num_steps: 5000
num_chains: 1
num_live_points: 25
display_progress: True
progress_verbose_print: True
folding_callback:
  _target_: language.folding_callbacks.EsmFoldv1
