_target_: programs.vhh_binder.vhh_binder_program
_partial_: true
energy_function_terms:
  - "MaximizePTM"
  - "MaximizePLDDT"
  - "MinimizeSurfaceHydrophobics"
  - "MaximizeIPTM"
energy_function_weights:
  - 1.0
  - 1.0
  - 1.0
  - 10.0

var1_program:
  _target_: language.program.ProgramNode
  sequence_segment:
    _target_: language.sequence.FixedLengthSequenceSegment
    initial_sequence: 8 # Median
    disallow_mutations_to_cysteine: True

var2_program:
  _target_: language.program.ProgramNode
  sequence_segment:
    _target_: language.sequence.FixedLengthSequenceSegment
    initial_sequence: 8 # Median
    disallow_mutations_to_cysteine: True

var3_program:
  _target_: language.program.ProgramNode
  sequence_segment:
    _target_: language.sequence.FixedLengthSequenceSegment
    initial_sequence: 16 # Median
    disallow_mutations_to_cysteine: True
