# path to root directory
# this requires PROJECT_ROOT environment variable to exist

scratch_dir: /home/ray/scratch_dir/

# path to data directory
data_dir: /mnt/shared_storage/target_pdbs/

# path to logging directory
log_dir: /home/ray/log/
