_target_: src.models.reg_llm_exploration_multihead.RegressionLLMExplorationMultiHead


optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.simple_transformer_encoder_multihead.SimpleTransformerModelMultiHead
  ntoken: 23
  d_model: 32 # embedding dimension
  d_hid: 32 # dimension of the feedforward network model
  nout: 32
  vector_head: 2
  scalar_head: false
  num_output_heads: 5
  nhead: 4
  nlayers: 2
  dropout: 0.1

# compile model for faster training with pytorch 2.0
compile: false

# exploration: masking
# exploration: probabilistic_masking
# exploration: bootstrap

plddt_loss_weight: 1.0

model_data_key_translate:
  aatype: src
  mask: src_key_padding_mask

target: dockq

