_target_: src.models.reg_llm_v0.RegressionLLMv0

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.simple_esm.SimpleESMV0
  esm_type: esm2_8M_270K
  pretrained: True,
  scalar_linear_layers: 2
  freeze_esm: False
  representation_layer: -1
  hsize: 256


# compile model for faster training with pytorch 2.0
compile: false

model_data_key_translate: null